### PR TITLE
changed echo to $reply->data = $tweets

### PR DESCRIPTION
**Pull request by akhamsamran**
Hi, I wanted to propose a change to the api index.php: the change is from echo  to $reply->data = $tweets;  
Thank you, 
Anna

### CODE REVIEW

**Comment by deepdivedylan** [comment]
No, this is just something committed by error. Can you just delete the `if` block? 😺

**Comment by akhamsamran** [comment]
yes, I have deleted the repeated if block

**Comment by deepdivedylan** [comment]
Well done, A♣️ K♣️! 😻 😹

**Comment by akhamsamran** [comment]
hooray!

**Pull request merged**
